version: '3.4'

services:
  appatlasdb:
    image: "postgres:15.6"
    restart: always
    container_name: appatlasdb
    env_file:
      - ./.env
    ports: 
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
volumes:
  db_data: 
